In [2]:
import torch
import numpy as np

In [3]:
torch.Tensor(5, 6)


1.00000e-25 *
  5.7532  0.0000  5.7532  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000  5.7529  0.0000
[torch.FloatTensor of size 5x6]

In [4]:
torch.rand(5, 6)



 0.4255  0.8615  0.3943  0.5181  0.3946  0.0720
 0.5205  0.4339  0.7206  0.6570  0.0990  0.1808
 0.0532  0.6567  0.4373  0.3021  0.8596  0.9567
 0.1716  0.1746  0.2777  0.8723  0.5680  0.9559
 0.6393  0.5197  0.2536  0.1147  0.8331  0.7674
[torch.FloatTensor of size 5x6]

In [5]:
a = torch.rand(5, 4)
a.size()

torch.Size([5, 4])

In [6]:
np.ones((5, 4))


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [7]:
np.zeros((5, 4))


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [8]:
a = torch.rand(5, 4)
b = a.numpy()
print(a,b)


 0.8655  0.1149  0.4356  0.8740
 0.5472  0.1586  0.7426  0.5074
 0.9943  0.9348  0.5390  0.7868
 0.0505  0.5762  0.0305  0.6977
 0.3173  0.9092  0.2568  0.6391
[torch.FloatTensor of size 5x4]
 [[ 0.86547786  0.11487174  0.435572    0.87403005]
 [ 0.54717761  0.15860301  0.74260151  0.50736386]
 [ 0.9942956   0.93481243  0.53898823  0.78681648]
 [ 0.0505379   0.57615387  0.03045985  0.69767261]
 [ 0.31726182  0.90919232  0.25681755  0.63912708]]


In [9]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)
print(b)


 3  4
 3  6
[torch.LongTensor of size 2x2]



In [10]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3

In [12]:
print(x,y)


 0.0888  0.6915  0.5736  0.9063
 0.1540  0.7482  0.4159  0.6069
 0.4838  0.0699  0.5373  0.7935
 0.9016  0.8040  0.7673  0.9650
 0.3030  0.2480  0.2610  0.1989
[torch.FloatTensor of size 5x4]
 
 0.7104  0.7139  0.8068  0.7258
 0.8893  0.6293  0.4545  0.1182
 0.0633  0.1634  0.6269  0.1467
 0.9598  0.6770  0.3620  0.2893
 0.6412  0.2177  0.8679  0.8357
[torch.FloatTensor of size 5x4]



In [11]:
print(c * x)


 0.2664  2.0745  1.7208  2.7189
 0.4621  2.2446  1.2477  1.8208
 1.4513  0.2098  1.6118  2.3805
 2.7047  2.4120  2.3019  2.8949
 0.9091  0.7441  0.7830  0.5968
[torch.FloatTensor of size 5x4]



In [13]:
print(x + y)


 0.7992  1.4054  1.3804  1.6321
 1.0433  1.3775  0.8704  0.7252
 0.5471  0.2333  1.1642  0.9402
 1.8614  1.4809  1.1293  1.2542
 0.9443  0.4657  1.1289  1.0346
[torch.FloatTensor of size 5x4]



In [14]:
print(x.add(y))


 0.7992  1.4054  1.3804  1.6321
 1.0433  1.3775  0.8704  0.7252
 0.5471  0.2333  1.1642  0.9402
 1.8614  1.4809  1.1293  1.2542
 0.9443  0.4657  1.1289  1.0346
[torch.FloatTensor of size 5x4]



In [15]:
x.add_(y)
print(x,y)


 0.7992  1.4054  1.3804  1.6321
 1.0433  1.3775  0.8704  0.7252
 0.5471  0.2333  1.1642  0.9402
 1.8614  1.4809  1.1293  1.2542
 0.9443  0.4657  1.1289  1.0346
[torch.FloatTensor of size 5x4]
 
 0.7104  0.7139  0.8068  0.7258
 0.8893  0.6293  0.4545  0.1182
 0.0633  0.1634  0.6269  0.1467
 0.9598  0.6770  0.3620  0.2893
 0.6412  0.2177  0.8679  0.8357
[torch.FloatTensor of size 5x4]



In [16]:
torch.cuda.is_available()

True

In [17]:
from torch.autograd import Variable

In [18]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y + 4

In [19]:
z.backward()

In [20]:
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: 
 2
[torch.FloatTensor of size 1]

dz/dy: 
 1
[torch.FloatTensor of size 1]



In [21]:
from torch import nn
import torch.nn.functional as F

In [22]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out